export type Lang = 'en' | 'hi'

const en = {
  nav: {
    home: 'Home',
    about: 'About Us',
    notifications: 'Notifications',
    faq: 'FAQ',
    login: 'Log In',
    register: 'Register',
    menu: 'Menu',
    closeMenu: 'Close menu',
    language: 'Language',
  },
  intro: {
    skip: 'Skip intro',
    generator: 'Waste generator',
    system: 'Punarchakra',
    route: 'Collector route',
    processor: 'Processor / buyer',
    value: 'Useful value',
    captions: [
      'Someone has waste.',
      'It moves to Punarchakra.',
      'Punarchakra analyses every option.',
      'The best route is found.',
      'A collector carries it forward.',
      'Waste becomes worth.',
    ],
  },
  hero: {
    eyebrow: 'Agricultural · Construction & Demolition',
    titleA: "Waste isn't worthless.",
    titleB: "It just hasn't found its next destination.",
    tagline: 'From Waste to Worth.',
    desc: 'Punarchakra finds the most viable path from waste to collection, processing and value.',
    primary: 'Get Started',
    secondary: 'See How It Works',
    flow: ['Waste', 'Analysis', 'Best Route', 'Collection', 'Processing', 'Value'],
    flowDesc: [
      'Crop residue or debris is logged.',
      'Type, quantity and location are read.',
      'The most viable destination is chosen.',
      'A collector is matched and booked.',
      'A facility turns it into material.',
      'Waste returns as worth.',
    ],
    flowLabel: 'Live system',
  },
  problem: {
    eyebrow: '01 — The problem',
    title: 'Most waste has no convenient destination.',
    desc: 'Not because it has no value, but because nobody connects it to the people who need it.',
    steps: [
      { title: 'Waste generated', desc: 'Harvest leaves residue. Sites leave debris.' },
      { title: 'No convenient option', desc: 'No buyer nearby. Transport costs too much.' },
      { title: 'Burned, dumped, piled up', desc: 'The easiest path becomes the default.' },
      { title: 'Value is lost', desc: 'Air, soil and income all pay the price.' },
    ],
  },
  solution: {
    eyebrow: '02 — The Punarchakra solution',
    title: 'The intelligent layer between waste and value.',
    desc: 'Punarchakra evaluates every option and recommends the one that actually works — then coordinates it.',
    generator: 'Waste generator',
    system: 'Punarchakra',
    collector: 'Collector',
    processor: 'Processor / buyer',
    evaluated: 'Evaluated',
    rejected: 'Not viable',
    chosen: 'Most viable',
    marketplaceTitle: 'A marketplace',
    marketplaceDesc: 'Lists options. You figure out distance, cost and capacity yourself.',
    systemTitle: 'Punarchakra',
    systemDesc: 'Weighs every option, picks the most viable path, and coordinates it end to end.',
  },
  streams: {
    eyebrow: '03 — Two waste streams',
    title: 'One engine. Two material flows.',
    becomes: 'Can become',
    agri: {
      label: 'Stream A',
      title: 'Agricultural waste',
      desc: 'Residue left after harvest — often burned because clearing it costs more than it earns.',
      items: ['Paddy / rice residue', 'Wheat residue', 'Sugarcane residue', 'Other crop residue'],
      outputs: ['Biomass pellets', 'Compost', 'Bio-CNG feedstock', 'Packaging board'],
      alt: 'Stylised harvested paddy field with stacked straw bales and a tractor with a baler',
    },
    cnd: {
      label: 'Stream B',
      title: 'Construction waste',
      desc: 'Debris from building and breaking — often dumped because sorting feels uneconomic.',
      items: ['Concrete', 'Bricks', 'Metal', 'Wood', 'Material scraps'],
      outputs: ['Recycled aggregate', 'New blocks & bricks', 'Scrap metal', 'Engineered wood'],
      alt: 'Stylised construction site with sorted piles of concrete, bricks, rebar and a tipper truck',
    },
  },
  how: {
    eyebrow: '04 — How it works',
    title: 'From a pile to a delivered load, in eight stops.',
    steps: [
      { title: 'Add waste', desc: 'Tell us what, how much and where.' },
      { title: 'Analyse', desc: 'Type, quality and quantity are assessed.' },
      { title: 'Find options', desc: 'Nearby collectors, processors and buyers.' },
      { title: 'Calculate economics', desc: 'Distance, cost, capacity and value.' },
      { title: 'Match & coordinate', desc: 'The most viable partners are booked.' },
      { title: 'Collect', desc: 'A collector picks up from your site.' },
      { title: 'Process', desc: 'The facility turns it into material.' },
      { title: 'Verify', desc: 'Every handover is confirmed.' },
    ],
  },
  economics: {
    eyebrow: '05 — The economic engine',
    title: 'Not just possible. Viable.',
    askOld: 'What can we do with this waste?',
    askNew: 'What is the most viable option?',
    desc: 'Punarchakra compares every destination on the factors that decide whether a pickup actually happens.',
    origin: 'Your waste',
    originDetail: '6 t paddy straw',
    evaluating: 'Evaluating',
    best: 'Best option',
    illustrative: 'Illustrative example',
    factorsTitle: 'What Punarchakra weighs',
    factors: [
      'Distance',
      'Transport cost',
      'Collector availability',
      'Processor capacity',
      'Waste quantity',
      'Aggregation',
      'Expected value',
      'Environmental impact',
    ],
    metrics: { distance: 'Distance', cost: 'Transport', capacity: 'Capacity', value: 'Net value' },
    options: [
      {
        id: 'A',
        name: 'Pellet plant, Ludhiana',
        verdict: 'Long distance · expensive',
        distance: '142 km',
        cost: 'High',
        capacity: 90,
        value: 22,
      },
      {
        id: 'B',
        name: 'Compost unit, nearby',
        verdict: 'Nearby · insufficient capacity',
        distance: '11 km',
        cost: 'Low',
        capacity: 18,
        value: 41,
      },
      {
        id: 'C',
        name: 'Bio-CNG plant, nearby',
        verdict: 'Nearby · capacity available',
        distance: '24 km',
        cost: 'Low',
        capacity: 76,
        value: 84,
      },
    ],
  },
  aggregation: {
    eyebrow: '06 — Aggregation',
    title: 'Small loads, combined, become worth collecting.',
    desc: 'One farm alone may be too small for a truck. Punarchakra pools nearby batches until a pickup pays for itself.',
    farmers: [
      { name: 'Farmer A', tonnes: 2 },
      { name: 'Farmer B', tonnes: 3 },
      { name: 'Farmer C', tonnes: 4 },
    ],
    tooSmall: 'Too small alone',
    combined: 'Combined',
    threshold: 'Minimum viable load · 8 t',
    viable: 'Viable together',
    processor: 'Processor',
    oneTrip: 'One trip · one route',
  },
  verify: {
    eyebrow: '07 — Verification',
    title: "It doesn't stop at a recommendation.",
    desc: 'Every load is tracked from booking to the processor’s confirmation — so everyone knows it really happened.',
    steps: ['Booked', 'Collected', 'Transported', 'Delivered', 'Processor confirmed'],
    proofs: ['GPS location', 'Timestamp', 'QR / OTP', 'Digital receipt'],
    receipt: {
      title: 'Digital receipt',
      id: 'PC-24817',
      material: 'Material',
      materialValue: 'Paddy straw · 9.2 t',
      pickup: 'Pickup',
      pickupValue: '30.90° N, 75.85° E',
      time: 'Collected',
      timeValue: '14 Oct · 09:42',
      otp: 'OTP handover',
      otpValue: 'Verified',
      processor: 'Processor',
      processorValue: 'Confirmed',
      scan: 'Scan to verify',
    },
  },
  faq: {
    eyebrow: '08 — Questions',
    title: 'Frequently asked questions',
    items: [
      {
        q: 'What is Punarchakra?',
        a: 'Punarchakra is a coordination platform that finds the most viable destination for your waste and connects you with collectors, processors and buyers who can use it.',
      },
      {
        q: 'Who can use it?',
        a: 'Farmers, construction workers and companies, waste collectors, transporters, processors and buyers of recovered material.',
      },
      {
        q: 'What types of waste are supported?',
        a: 'Agricultural residue such as paddy, wheat, sugarcane and cotton residue, and construction & demolition waste such as concrete, bricks, metal and wood.',
      },
      {
        q: 'How does Punarchakra find the best option?',
        a: 'It compares distance, transport cost, collector availability, processor capacity, quantity and expected value, then recommends the path that is most likely to work.',
      },
      {
        q: 'Can multiple farmers or sites combine waste?',
        a: 'Yes. When single batches are too small, Punarchakra groups nearby batches into one viable pickup.',
      },
      {
        q: 'Does Punarchakra arrange transportation?',
        a: 'Punarchakra matches you with a collector or transporter and coordinates the pickup, route and handover.',
      },
      {
        q: 'What happens if no viable option exists?',
        a: 'We tell you clearly, suggest what would make it viable — like waiting to aggregate more — and notify you when a new option appears.',
      },
    ],
  },
  cta: {
    title: 'Give your waste its next destination.',
    desc: 'Connect waste with the people, routes and facilities that can turn it into value.',
    primary: 'Get Started',
    secondary: 'See How It Works',
  },
  footer: {
    tagline: 'From Waste to Worth.',
    rights: 'All rights reserved.',
  },
  auth: {
    loginTitle: 'Log in to Punarchakra',
    loginDesc: 'Use the phone number you registered with.',
    registerTitle: 'Create your account',
    registerDesc: 'Tell us who you are so we can show the right options.',
    name: 'Full name',
    phone: 'Phone number',
    password: 'Password',
    role: 'I am a',
    roles: ['Waste generator', 'Collector', 'Processor / buyer'],
    submitLogin: 'Log In',
    submitRegister: 'Register',
    switchToRegister: 'New here? Register',
    switchToLogin: 'Already registered? Log in',
    soonTitle: 'Thank you',
    soonDesc: 'Accounts are opening soon. We will message you on this number when Punarchakra is live in your area.',
    close: 'Close',
  },
  notifications: {
    title: 'Notifications',
    desc: 'Pickup updates, new buyers and route alerts will appear here.',
    emptyTitle: 'No notifications yet',
    emptyDesc: 'Log in or register to receive updates about your waste.',
    preview: 'You will see updates like',
    examples: ['A collector accepted your pickup', 'A new buyer is near your area', 'Your load was confirmed'],
  },
}

export type Content = typeof en

const hi: Content = {
  nav: {
    home: 'होम',
    about: 'हमारे बारे में',
    notifications: 'सूचनाएँ',
    faq: 'सवाल-जवाब',
    login: 'लॉग इन',
    register: 'रजिस्टर',
    menu: 'मेन्यू',
    closeMenu: 'मेन्यू बंद करें',
    language: 'भाषा',
  },
  intro: {
    skip: 'इंट्रो छोड़ें',
    generator: 'कचरा उत्पादक',
    system: 'पुनर्चक्र',
    route: 'कलेक्टर रूट',
    processor: 'प्रोसेसर / खरीदार',
    value: 'उपयोगी मूल्य',
    captions: [
      'किसी के पास कचरा है।',
      'वह पुनर्चक्र तक पहुँचता है।',
      'पुनर्चक्र हर विकल्प को परखता है।',
      'सबसे अच्छा रास्ता मिलता है।',
      'कलेक्टर उसे आगे ले जाता है।',
      'कचरा बनता है कीमत।',
    ],
  },
  hero: {
    eyebrow: 'कृषि · निर्माण और विध्वंस',
    titleA: 'कचरा बेकार नहीं है।',
    titleB: 'बस उसे अभी अपनी अगली मंज़िल नहीं मिली।',
    tagline: 'कचरे से कीमत तक।',
    desc: 'पुनर्चक्र कचरे के लिए संग्रह, प्रोसेसिंग और मूल्य तक का सबसे व्यावहारिक रास्ता ढूँढता है।',
    primary: 'शुरू करें',
    secondary: 'देखें यह कैसे काम करता है',
    flow: ['कचरा', 'विश्लेषण', 'सबसे अच्छा रूट', 'संग्रह', 'प्रोसेसिंग', 'मूल्य'],
    flowDesc: [
      'पराली या मलबा दर्ज किया जाता है।',
      'प्रकार, मात्रा और जगह पढ़ी जाती है।',
      'सबसे व्यावहारिक मंज़िल चुनी जाती है।',
      'कलेक्टर तय और बुक होता है।',
      'फैक्ट्री उसे सामग्री में बदलती है।',
      'कचरा कीमत बनकर लौटता है।',
    ],
    flowLabel: 'लाइव सिस्टम',
  },
  problem: {
    eyebrow: '01 — समस्या',
    title: 'ज़्यादातर कचरे के लिए कोई आसान मंज़िल नहीं होती।',
    desc: 'इसलिए नहीं कि उसकी कोई कीमत नहीं, बल्कि इसलिए कि कोई उसे ज़रूरतमंद तक नहीं जोड़ता।',
    steps: [
      { title: 'कचरा बनता है', desc: 'फसल के बाद पराली, साइट पर मलबा।' },
      { title: 'कोई आसान विकल्प नहीं', desc: 'पास में खरीदार नहीं, ढुलाई महँगी।' },
      { title: 'जलाना, फेंकना, ढेर लगाना', desc: 'सबसे आसान रास्ता ही आदत बन जाता है।' },
      { title: 'मूल्य खो जाता है', desc: 'हवा, मिट्टी और आमदनी — सब पर असर।' },
    ],
  },
  solution: {
    eyebrow: '02 — पुनर्चक्र का समाधान',
    title: 'कचरे और मूल्य के बीच की समझदार कड़ी।',
    desc: 'पुनर्चक्र हर विकल्प को परखता है, जो सच में काम करे वही सुझाता है — और फिर उसे पूरा करवाता है।',
    generator: 'कचरा उत्पादक',
    system: 'पुनर्चक्र',
    collector: 'कलेक्टर',
    processor: 'प्रोसेसर / खरीदार',
    evaluated: 'परखा गया',
    rejected: 'व्यावहारिक नहीं',
    chosen: 'सबसे व्यावहारिक',
    marketplaceTitle: 'एक मार्केटप्लेस',
    marketplaceDesc: 'विकल्प दिखाता है। दूरी, लागत और क्षमता आपको खुद देखनी होती है।',
    systemTitle: 'पुनर्चक्र',
    systemDesc: 'हर विकल्प तौलता है, सबसे व्यावहारिक रास्ता चुनता है और शुरू से अंत तक संभालता है।',
  },
  streams: {
    eyebrow: '03 — दो तरह का कचरा',
    title: 'एक इंजन। दो सामग्री प्रवाह।',
    becomes: 'बन सकता है',
    agri: {
      label: 'धारा A',
      title: 'कृषि कचरा',
      desc: 'कटाई के बाद बची पराली — अक्सर जला दी जाती है क्योंकि हटाना कमाई से महँगा पड़ता है।',
      items: ['धान की पराली', 'गेहूँ का अवशेष', 'गन्ने का अवशेष', 'कपास का अवशेष', 'अन्य फसल अवशेष'],
      outputs: ['बायोमास पेलेट', 'कम्पोस्ट', 'बायो-CNG कच्चा माल', 'पैकेजिंग बोर्ड'],
      alt: 'कटे हुए धान के खेत में पराली की गाँठें और बेलर के साथ ट्रैक्टर',
    },
    cnd: {
      label: 'धारा B',
      title: 'निर्माण और विध्वंस कचरा',
      desc: 'बनाने और तोड़ने से निकला मलबा — अक्सर फेंक दिया जाता है क्योंकि छँटाई और ढुलाई महँगी लगती है।',
      items: ['कंक्रीट', 'ईंटें', 'धातु', 'लकड़ी', 'बची हुई सामग्री'],
      outputs: ['रीसाइकल्ड एग्रीगेट', 'नए ब्लॉक और ईंटें', 'स्क्रैप धातु', 'इंजीनियर्ड लकड़ी'],
      alt: 'निर्माण स्थल पर छँटे हुए कंक्रीट, ईंट, सरिया के ढेर और टिपर ट्रक',
    },
  },
  how: {
    eyebrow: '04 — यह कैसे काम करता है',
    title: 'ढेर से डिलीवर हुए लोड तक, आठ पड़ाव।',
    steps: [
      { title: 'कचरा जोड़ें', desc: 'क्या, कितना और कहाँ — बताइए।' },
      { title: 'विश्लेषण', desc: 'प्रकार, गुणवत्ता और मात्रा की जाँच।' },
      { title: 'विकल्प खोजें', desc: 'पास के कलेक्टर, प्रोसेसर और खरीदार।' },
      { title: 'हिसाब लगाएँ', desc: 'दूरी, लागत, क्षमता और मूल्य।' },
      { title: 'मिलान और तालमेल', desc: 'सबसे व्यावहारिक साझेदार बुक।' },
      { title: 'संग्रह', desc: 'कलेक्टर आपकी जगह से उठाता है।' },
      { title: 'प्रोसेसिंग', desc: 'फैक्ट्री उसे सामग्री में बदलती है।' },
      { title: 'पुष्टि', desc: 'हर हैंडओवर की पुष्टि होती है।' },
    ],
  },
  economics: {
    eyebrow: '05 — आर्थिक इंजन',
    title: 'सिर्फ़ संभव नहीं। व्यावहारिक।',
    askOld: 'इस कचरे का क्या कर सकते हैं?',
    askNew: 'सबसे व्यावहारिक विकल्प कौन-सा है?',
    desc: 'पुनर्चक्र हर मंज़िल को उन बातों पर तौलता है जो तय करती हैं कि पिकअप सच में होगा या नहीं।',
    origin: 'आपका कचरा',
    originDetail: '6 टन धान की पराली',
    evaluating: 'परख रहे हैं',
    best: 'सबसे अच्छा विकल्प',
    illustrative: 'उदाहरण के लिए',
    factorsTitle: 'पुनर्चक्र क्या-क्या तौलता है',
    factors: [
      'दूरी',
      'ढुलाई लागत',
      'कलेक्टर की उपलब्धता',
      'प्रोसेसर की क्षमता',
      'कचरे की मात्रा',
      'एकत्रीकरण',
      'अनुमानित मूल्य',
      'पर्यावरण पर असर',
    ],
    metrics: { distance: 'दूरी', cost: 'ढुलाई', capacity: 'क्षमता', value: 'शुद्ध मूल्य' },
    options: [
      {
        id: 'A',
        name: 'पेलेट प्लांट, लुधियाना',
        verdict: 'बहुत दूर · महँगा',
        distance: '142 किमी',
        cost: 'ज़्यादा',
        capacity: 90,
        value: 22,
      },
      {
        id: 'B',
        name: 'कम्पोस्ट यूनिट, पास में',
        verdict: 'पास में · क्षमता कम',
        distance: '11 किमी',
        cost: 'कम',
        capacity: 18,
        value: 41,
      },
      {
        id: 'C',
        name: 'बायो-CNG प्लांट, पास में',
        verdict: 'पास में · क्षमता उपलब्ध',
        distance: '24 किमी',
        cost: 'कम',
        capacity: 76,
        value: 84,
      },
    ],
  },
  aggregation: {
    eyebrow: '06 — एकत्रीकरण',
    title: 'छोटे लोड मिलकर उठाने लायक बन जाते हैं।',
    desc: 'अकेला खेत ट्रक के लिए छोटा हो सकता है। पुनर्चक्र पास के लोड जोड़ता है, जब तक पिकअप फ़ायदेमंद न हो जाए।',
    farmers: [
      { name: 'किसान A', tonnes: 2 },
      { name: 'किसान B', tonnes: 3 },
      { name: 'किसान C', tonnes: 4 },
    ],
    tooSmall: 'अकेले बहुत छोटा',
    combined: 'कुल मिलाकर',
    threshold: 'न्यूनतम व्यावहारिक लोड · 8 टन',
    viable: 'साथ मिलकर व्यावहारिक',
    processor: 'प्रोसेसर',
    oneTrip: 'एक ट्रिप · एक रूट',
  },
  verify: {
    eyebrow: '07 — पुष्टि',
    title: 'सिर्फ़ सुझाव देकर नहीं रुकता।',
    desc: 'हर लोड बुकिंग से लेकर प्रोसेसर की पुष्टि तक ट्रैक होता है — ताकि सबको पता हो कि काम सच में हुआ।',
    steps: ['बुक हुआ', 'उठाया गया', 'ढुलाई', 'पहुँचाया गया', 'प्रोसेसर ने पुष्टि की'],
    proofs: ['GPS लोकेशन', 'समय-मुहर', 'QR / OTP', 'डिजिटल रसीद'],
    receipt: {
      title: 'डिजिटल रसीद',
      id: 'PC-24817',
      material: 'सामग्री',
      materialValue: 'धान की पराली · 9.2 टन',
      pickup: 'पिकअप',
      pickupValue: '30.90° N, 75.85° E',
      time: 'उठाया गया',
      timeValue: '14 अक्टूबर · 09:42',
      otp: 'OTP हैंडओवर',
      otpValue: 'सत्यापित',
      processor: 'प्रोसेसर',
      processorValue: 'पुष्टि हुई',
      scan: 'जाँचने के लिए स्कैन करें',
    },
  },
  faq: {
    eyebrow: '08 — सवाल',
    title: 'अक्सर पूछे जाने वाले सवाल',
    items: [
      {
        q: 'पुनर्चक्र क्या है?',
        a: 'पुनर्चक्र एक तालमेल प्लेटफ़ॉर्म है जो आपके कचरे के लिए सबसे व्यावहारिक मंज़िल ढूँढता है और आपको कलेक्टर, प्रोसेसर और खरीदारों से जोड़ता है।',
      },
      {
        q: 'इसे कौन इस्तेमाल कर सकता है?',
        a: 'किसान, निर्माण मज़दूर और कंपनियाँ, कचरा कलेक्टर, ट्रांसपोर्टर, प्रोसेसर और रीसाइकल सामग्री के खरीदार।',
      },
      {
        q: 'किस तरह का कचरा शामिल है?',
        a: 'धान, गेहूँ, गन्ना और कपास जैसे फसल अवशेष, और कंक्रीट, ईंट, धातु व लकड़ी जैसा निर्माण और विध्वंस कचरा।',
      },
      {
        q: 'पुनर्चक्र सबसे अच्छा विकल्प कैसे ढूँढता है?',
        a: 'यह दूरी, ढुलाई लागत, कलेक्टर की उपलब्धता, प्रोसेसर की क्षमता, मात्रा और अनुमानित मूल्य की तुलना करके वह रास्ता सुझाता है जो सबसे ज़्यादा कारगर हो।',
      },
      {
        q: 'क्या कई किसान या साइटें कचरा मिला सकते हैं?',
        a: 'हाँ। जब अकेला लोड छोटा हो, तो पुनर्चक्र पास के लोड जोड़कर एक व्यावहारिक पिकअप बनाता है।',
      },
      {
        q: 'क्या पुनर्चक्र ढुलाई का इंतज़ाम करता है?',
        a: 'पुनर्चक्र आपको कलेक्टर या ट्रांसपोर्टर से जोड़ता है और पिकअप, रूट और हैंडओवर का तालमेल करता है।',
      },
      {
        q: 'अगर कोई व्यावहारिक विकल्प न हो तो?',
        a: 'हम साफ़ बताते हैं, सुझाते हैं कि क्या करने से यह व्यावहारिक बनेगा — जैसे और लोड जुड़ने का इंतज़ार — और नया विकल्प आते ही सूचना देते हैं।',
      },
    ],
  },
  cta: {
    title: 'अपने कचरे को उसकी अगली मंज़िल दीजिए।',
    desc: 'कचरे को उन लोगों, रास्तों और फैक्ट्रियों से जोड़िए जो उसे मूल्य में बदल सकते हैं।',
    primary: 'शुरू करें',
    secondary: 'देखें यह कैसे काम करता है',
  },
  footer: {
    tagline: 'कचरे से कीमत तक।',
    rights: 'सर्वाधिकार सुरक्षित।',
  },
  auth: {
    loginTitle: 'पुनर्चक्र में लॉग इन करें',
    loginDesc: 'वही फ़ोन नंबर डालें जिससे आपने रजिस्टर किया था।',
    registerTitle: 'अपना खाता बनाएँ',
    registerDesc: 'बताइए आप कौन हैं, ताकि हम सही विकल्प दिखा सकें।',
    name: 'पूरा नाम',
    phone: 'फ़ोन नंबर',
    password: 'पासवर्ड',
    role: 'मैं हूँ',
    roles: ['कचरा उत्पादक', 'कलेक्टर', 'प्रोसेसर / खरीदार'],
    submitLogin: 'लॉग इन',
    submitRegister: 'रजिस्टर',
    switchToRegister: 'नए हैं? रजिस्टर करें',
    switchToLogin: 'पहले से रजिस्टर हैं? लॉग इन करें',
    soonTitle: 'धन्यवाद',
    soonDesc: 'खाते जल्द ही खुलेंगे। आपके इलाके में पुनर्चक्र शुरू होते ही हम इसी नंबर पर संदेश भेजेंगे।',
    close: 'बंद करें',
  },
  notifications: {
    title: 'सूचनाएँ',
    desc: 'पिकअप अपडेट, नए खरीदार और रूट अलर्ट यहाँ दिखेंगे।',
    emptyTitle: 'अभी कोई सूचना नहीं',
    emptyDesc: 'अपने कचरे के अपडेट पाने के लिए लॉग इन या रजिस्टर करें।',
    preview: 'आपको ऐसे अपडेट दिखेंगे',
    examples: ['कलेक्टर ने आपका पिकअप स्वीकार किया', 'आपके इलाके में नया खरीदार', 'आपके लोड की पुष्टि हुई'],
  },
}

export const content: Record<Lang, Content> = { en, hi }
